<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
  <script>
    const fetchData1 = () => {
      const data = fetch("https://jsonplaceholder.typicode.com/posts");
      data
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }

          console.log(response);
          return response.json();
        })
        .then((json) => {
          console.log("Response:", json);

          const firstPost = json[0];
          console.log("First Post:", firstPost);

          return fetch(
            `https://jsonplaceholder.typicode.com/posts/${firstPost.id}`
          );
        })
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }
          return response.json();
        })
        .then((postDetails) => {
          console.log("Post Details:", postDetails);
        })
        .catch((error) => {
          console.error("Error fetching data:", error);
        });

      console.log("Here!");
    };

    /*     async function name(params) {
      
    } */

    const fetchData2 = async () => {
      try {
        const postsResponse = await fetch(
          "https://jsonplaceholder.typicode.com/posts"
        );

        if (!postsResponse.ok) {
          throw new Error("Network response was not ok");
        }

        const posts = await postsResponse.json();
        console.log("Posts:", posts);

        const firstPost = posts[0];
        console.log("First Post:", firstPost);

        const postDetailsResponse = await fetch(
          `https://jsonplaceholder.typicode.com/posts/${firstPost.id}`
        );

        if (!postDetailsResponse.ok) {
          throw new Error("Network response was not ok");
        }

        const postDetails = await postDetailsResponse.json();

        console.log("Post Details:", postDetails);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    //fetchData2();

    console.log("Hello from outside!");

    const wait = (timeout) => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("Done!");
        }, timeout);
      });
    };

    const simulateApiWithFail = () => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          const random = Math.random();
          if (random < 0.5) {
            resolve("Success!");
          } else {
            reject(new Error("Failed!"));
          }
        }, 2000);
      });
    };

    const example = async () => {
      console.log("Waiting...");
      const result = await wait(2000);
      console.log(result);
      console.log("Done waiting!");
    };

    const example2 = async () => {
      try {
        const result = await simulateApiWithFail();
        console.log(result);
      } catch (error) {
        console.error("Error:", error);
      }
    };

    //example();
    example2();
  </script>
</html>
